from sqlalchemy import Table, Column,REAL, Integer, BigInteger, Text, Float, MetaData, ForeignKey, String, Boolean

metadata = MetaData()

event = Table(
    "event", metadata,
    Column("eventid", Integer, primary_key=True),
    Column("iyear", Integer),
    Column("imonth", Integer),
    Column("iday", Integer),
    Column("location", Text),
    Column("summary", Text),
    Column("latitude", REAL),
    Column("longitude", REAL),
    Column("crit1", Integer),
    Column("crit2", Integer),
    Column("crit3", Integer),
    Column("addnotes", Text),
    Column("scite1", Text),
    Column("scite2", Text),
    Column("scite3", Text),
    Column("dbsource", Text),
    Column("targetid", Integer, ForeignKey("target.targetid")),
    Column("gid", Integer, ForeignKey("group.gid")),
    Column("weaponid", Integer, ForeignKey("weapon.weaponid")),
    Column("attackid", Integer, ForeignKey("attack.attackid")),
    Column("nkill", BigInteger),
    Column("nkillus", Integer),
    Column("nkillter", Integer),
    Column("nwound", BigInteger),
    Column("nwoundte", Integer),
    Column("property", Integer),
    Column("propextent", Integer),
    Column("propextent_txt", String(20)),
    Column("propvalue", BigInteger),
    Column("propcomment", String(15)),
    Column("ishostkid", Integer),
    Column("nhostkid", Integer),
    Column("nhostkidus", Integer),
    Column("nhours", Integer),
    Column("ndays", Integer),
    Column("divert", String(15)),
    Column("kidihijcountry", String(20)),
    Column("ransom", Integer),
    Column("ransomamt", BigInteger),
    Column("ransomamtus", String(20)),
    Column("ransompaid", Integer),
    Column("ransompaidus", String(20)),
    Column("ransomnote", String(100)),
    Column("hostkidoutcome", Integer),
    Column("hostkidoutcome_txt", String(20)),
    Column("nreleased", Integer),
    Column("regionid", Integer, ForeignKey("region.regionid")),
    Column("countryid", Integer, ForeignKey("country.countryid")),
)
weapon = Table(
    "weapon", metadata,
    Column("weaponid", Integer, primary_key=True),
    Column("weaptype1", Integer),
    Column("weaptype1_txt", String(100)),
    Column("weapsubtype1", Integer),
    Column("weapsubtype1_txt", String(100)),
    Column("weaptype2", Integer),
    Column("weaptype2_txt", String(100)),
    Column("weapsubtype2", Integer),
    Column("weapsubtype2_txt", String(100)),
    Column("weaptype3", Integer),
    Column("weaptype3_txt", String(100)),
    Column("weapsubtype3", Integer),
    Column("weapsubtype3_txt", String(100)),
    Column("weaptype4", Integer),
    Column("weaptype4_txt", String(100)),
    Column("weapsubtype4", Integer),
    Column("weapsubtype4_txt", String(100)),
    Column("weapdetail", Text),
)

target = Table(
    "target", metadata,
    Column("targetid", Integer, primary_key=True),
    Column("targtype1", Integer),
    Column("targtype1_txt", Text),
    Column("targsubtype1", Integer),
    Column("targsubtype1_txt", Text),
    Column("corp1", Text),
    Column("target1", Text),
    Column("natlty1", Integer),
    Column("natlty1_txt", Text),
    Column("targtype2", Integer),
    Column("targtype2_txt", Text),
    Column("targsubtype2", Integer),
    Column("targsubtype2_txt", Text),
    Column("corp2", Text),
    Column("target2", Text),
    Column("natlty2", Integer),
    Column("natlty2_txt", Text),
    Column("targtype3", Integer),
    Column("targtype3_txt", Text),
    Column("targsubtype3", Integer),
    Column("targsubtype3_txt", Text),
    Column("corp3", Text),
    Column("target3", Text),
    Column("natlty3", Integer),
    Column("natlty3_txt", Text),
    Column("countryid", Integer, ForeignKey("country.countryid")),
    Column("regionid", Integer, ForeignKey("region.regionid")),
)

group = Table(
    "group", metadata,
    Column("gid", Integer, primary_key=True),
    Column("gname", String(100)),
    Column("gsubname", String(100)),
    Column("gname2", String(100)),
    Column("gsubname2", String(100)),
    Column("gname3", String(100)),
    Column("gsubname3", String(100)),
    Column("motive", Text),
    Column("guncertain1", Integer),
    Column("guncertain2", Integer),
    Column("guncertain3", Integer),
    Column("individual", Integer),
    Column("nperps", Integer),
    Column("nperpcap", Integer),
    Column("claimed", Integer),
    Column("claimmode", Integer),
    Column("claimmode_txt", String(100)),
    Column("claim2", Integer),
    Column("claimmode2", Integer),
    Column("claimmode2_txt", String(100)),
    Column("claim3", Integer),
    Column("claimmode3", Integer),
    Column("claimmode3_txt", String(100)),
    Column("compclaim", Text),
)

region = Table(
    "region", metadata,
    Column("regionid", Integer, primary_key=True),
    Column("region", String(200)),
)

fatality = Table(
    "fatality", metadata,
    Column("fatalityid", Integer, primary_key=True),
    Column("nkill", BigInteger),
    Column("nkillus", Integer),
    Column("nkillter", Integer),
    Column("nwound", BigInteger),
    Column("nwoundte", Integer),
    Column("property", Integer),
    Column("propextent", Integer),
    Column("propextent_txt", String(20)),
    Column("propvalue", BigInteger),
    Column("propcomment", String(15)),
    Column("ishostkid", Integer),
    Column("nhostkid", Integer),
    Column("nhostkidus", Integer),
    Column("nhours", Integer),
    Column("ndays", Integer),
    Column("divert", String(15)),
    Column("kidihijcountry", String(20)),
    Column("ransom", Integer),
    Column("ransomamt", BigInteger),
    Column("ransomamtus", String(20)),
    Column("ransompaid", Integer),
    Column("ransompaidus", String(20)),
    Column("ransomnote", String(100)),
    Column("hostkidoutcome", Integer),
    Column("hostkidoutcome_txt", String(20)),
    Column("nreleased", Integer),
)

country = Table(
    "country", metadata,
    Column("countryid", Integer, primary_key=True),
    Column("countrycode", Integer),
    Column("country", String(100)),
    Column("provstate", String(100)),
    Column("city", String(100)),
    Column("regionid", Integer, ForeignKey("region.regionid")),
)

attack = Table(
    "attack", metadata,
    Column("attackid", Integer, primary_key=True),
    Column("attacktype", String(50)),

)